package com.pta.entities;
// Generated Mar 29, 2024, 8:12:15 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Genres generated by hbm2java
 */
@Entity
@Table(name = "genres", catalog = "pta_game")
public class Genres implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<GameGenres> gameGenreses = new HashSet<GameGenres>(0);

	public Genres() {
	}

	public Genres(String name) {
		this.name = name;
	}

	public Genres(String name, Set<GameGenres> gameGenreses) {
		this.name = name;
		this.gameGenreses = gameGenreses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genres")
	public Set<GameGenres> getGameGenreses() {
		return this.gameGenreses;
	}

	public void setGameGenreses(Set<GameGenres> gameGenreses) {
		this.gameGenreses = gameGenreses;
	}

}
