package com.pta.entities;
// Generated Mar 29, 2024, 8:12:15 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * OperatingSystem generated by hbm2java
 */
@Entity
@Table(name = "operating_system")
public class OperatingSystem implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String operatingSystem;
	private String processor;
	private String memory;
	private String graphics;
	private String directX;
	private String storage;
	private String soundCard;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm")
	private Date createdTime;
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm")
	private Date updatedTime;

	public OperatingSystem() {
	}

	public OperatingSystem(Product product, String operatingSystem, String processor, String memory, String graphics,
			String directX, String storage, String soundCard, Date createdTime) {
		this.product = product;
		this.operatingSystem = operatingSystem;
		this.processor = processor;
		this.memory = memory;
		this.graphics = graphics;
		this.directX = directX;
		this.storage = storage;
		this.soundCard = soundCard;
		this.createdTime = createdTime;
	}

	public OperatingSystem(Product product, String operatingSystem, String processor, String memory, String graphics,
			String directX, String storage, String soundCard, Date createdTime, Date updatedTime) {
		this.product = product;
		this.operatingSystem = operatingSystem;
		this.processor = processor;
		this.memory = memory;
		this.graphics = graphics;
		this.directX = directX;
		this.storage = storage;
		this.soundCard = soundCard;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "operatingSystem", nullable = false, length = 250)
	public String getOperatingSystem() {
		return this.operatingSystem;
	}

	public void setOperatingSystem(String operatingSystem) {
		this.operatingSystem = operatingSystem;
	}

	@Column(name = "processor", nullable = false, length = 250)
	public String getProcessor() {
		return this.processor;
	}

	public void setProcessor(String processor) {
		this.processor = processor;
	}

	@Column(name = "memory", nullable = false, length = 250)
	public String getMemory() {
		return this.memory;
	}

	public void setMemory(String memory) {
		this.memory = memory;
	}

	@Column(name = "graphics", nullable = false, length = 250)
	public String getGraphics() {
		return this.graphics;
	}

	public void setGraphics(String graphics) {
		this.graphics = graphics;
	}

	@Column(name = "directX", nullable = false, length = 250)
	public String getDirectX() {
		return this.directX;
	}

	public void setDirectX(String directX) {
		this.directX = directX;
	}

	@Column(name = "storage", nullable = false, length = 250)
	public String getStorage() {
		return this.storage;
	}

	public void setStorage(String storage) {
		this.storage = storage;
	}

	@Column(name = "soundCard", nullable = false, length = 250)
	public String getSoundCard() {
		return this.soundCard;
	}

	public void setSoundCard(String soundCard) {
		this.soundCard = soundCard;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
