package com.pta.entities;
// Generated Mar 29, 2024, 8:12:15 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;


/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private Integer id;
	private Developer developer;
	private Publisher publisher;
	private String name;
	private String description;
	private String image;
	private String price;
	private int status;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm")
	private Date createdTime;
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm")
	private Date updatedTime;
	
	private Set<GameGenres> gameGenreses = new HashSet<GameGenres>(0);
	private Set<OperatingSystem> operatingSystems = new HashSet<OperatingSystem>(0);

	public Product() {
	}

	public Product(String name, String description, String image, String price, int status, Date createdTime) {
		this.name = name;
		this.description = description;
		this.image = image;
		this.price = price;
		this.status = status;
		this.createdTime = createdTime;
	}

	public Product(Developer developer, Publisher publisher, String name, String description, String image,
			String price, int status, Date createdTime, Date updatedTime, Set<GameGenres> gameGenreses,
			Set<OperatingSystem> operatingSystems) {
		this.developer = developer;
		this.publisher = publisher;
		this.name = name;
		this.description = description;
		this.image = image;
		this.price = price;
		this.status = status;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.gameGenreses = gameGenreses;
		this.operatingSystems = operatingSystems;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "developer_id")
	public Developer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Developer developer) {
		this.developer = developer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publisher_id")
	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image", nullable = false, length = 250)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "price", nullable = false, length = 250)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "status", nullable = false, length = 11)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<GameGenres> getGameGenreses() {
		return this.gameGenreses;
	}

	public void setGameGenreses(Set<GameGenres> gameGenreses) {
		this.gameGenreses = gameGenreses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OperatingSystem> getOperatingSystems() {
		return this.operatingSystems;
	}

	public void setOperatingSystems(Set<OperatingSystem> operatingSystems) {
		this.operatingSystems = operatingSystems;
	}

}
